server:
  port: 8765

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/users/**

        - id: ENT-AUTHENTICATION-SERVICE
          uri: lb://ENT-AUTHENTICATION-SERVICE
          predicates:
          - Path=/api/auth/**

        - id: DISCOVERY-SERVICE
          uri: http://localhost:8761/
          predicates:
          - Path=/eureka/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
